// src/pages/Home.svelte
<script lang="ts">
  import DisplayGrid from '../components/DisplayGrid.svelte';
  import Layout from '../components/Layout.svelte';
  import { available, loading } from '../store';
</script>

<Layout>
  {#if $loading}
    <h2>Loading...</h2>
  {:else}
    <DisplayGrid emoji={$available} />
  {/if}
</Layout>

// src/pages/Home.tsx
import { type FC } from 'react';

import { Layout } from '$components/layout/Layout';
import { DisplayGrid } from '$components/displayGrid/DisplayGrid';
import { useEmojiContext } from '$context';

export const Home: FC = () => {
	const { available, loading } = useEmojiContext();

	return (
		<Layout>
			{loading ? <h2>Loading...</h2> : <DisplayGrid emoji={available} />}
		</Layout>
	);
};
