// src/components/modal/Modal.tsx
import { type FC, useEffect, useRef } from 'react';

import { type Emoji as EmojiType } from '$api';
import { Emoji } from '$components/emoji/Emoji';
import { Button } from '$components/button/Button';

import styles from './Modal.module.css';

interface Properties {
  emoji?: EmojiType;
  onClose: () => void;
  onSelection: () => void;
}

export const Modal: FC<Properties> = ({ emoji, onClose, onSelection }) => {
	const dialogReference = useRef<HTMLDialogElement>(null);

	useEffect(() => {
		if (!dialogReference.current || emoji === undefined) {
			return;
		}

		dialogReference.current.showModal();
	}, [emoji, dialogReference]);

	return (
		emoji && (
			<dialog ref={dialogReference}>
				<Emoji emoji={emoji} disableSelection={true} />

				<div className={styles.buttons}>
					<Button onClick={onSelection}>Add to Selection</Button>

					<Button onClick={onClose}>Close</Button>
				</div>
			</dialog>
		)
	);
};

// src/components/Modal.svelte
<script lang="ts">
  import { type Emoji as EmojiType } from '../api';
  import Button from './Button.svelte';
  import Emoji from './Emoji.svelte';

  export let emoji: EmojiType | undefined;
  export let onClose: () => void;
  export let onSelection: () => void;

  let dialog: HTMLDialogElement | undefined;

  $: emoji !== undefined && dialog?.showModal();
</script>

{#if emoji !== undefined}
  <dialog bind:this={dialog}>
    <Emoji {emoji} disableSelection={true} />

    <div class="buttons">
      <Button on:click={onSelection}>Add to Selection</Button>

      <Button on:click={onClose}>Close</Button>
    </div>
  </dialog>
{/if}

<style>
  @import "../styles/sizing.css";

  :modal {
    width: 100vw;
    height: 100vh;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: var(--sizing-gap);

    background-color: rgba(1, 1, 1, 0.1);
  }

  .buttons {
    display: flex;
    flex: row;
    gap: var(--sizing-gap);
  }
</style>
